name: ${project.name}
author: TrueMB
version: ${project.version}
api-version: 1.16
main: me.truemb.rentit.main.Main
depend: [WorldEdit, Vault]
softdepend: [WorldGuard, Citizens, PlaceholderAPI, AdvancedChests]